[project]
name = "description-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.54",
    "langchain-openai>=0.3.14",
    "langchain>=0.3.23",
]
